approval_policy = "on-request"
sandbox_mode    = "workspace-write"
network_access = true

[mcp_servers.cloudflare]
command = "npx"
args = ["mcp-remote", "https://docs.mcp.cloudflare.com/sse"]

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]
