approval_policy = "on-request"
sandbox_mode    = "workspace-write"
network_access = true
[mcp_servers.cloudflare]
archived = true
notes = "Cloudflare MCP server entry removed/archived as part of Cloudflare purge. Original entry is preserved in the repo history."

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]
