version: '3.8'

services:
  web:
    build:
      context: .
      target: runner
    ports:
      - '3000:3000'
    volumes:
      - database:/app/database
      - storage:/app/storage
      - local_storage:/app/.local-storage
      - logs:/app/logs
    env_file:
      - .env
    environment:
      NODE_ENV: production
      VERTICAL_TEXT_GENERATOR_URL: http://vertical-text-generator:8000
    restart: unless-stopped
    depends_on:
      - vertical-text-generator
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  worker:
    build:
      context: .
      target: runner
    volumes:
      - database:/app/database
      - storage:/app/storage
      - local_storage:/app/.local-storage
      - logs:/app/logs
    env_file:
      - .env
    environment:
      NODE_ENV: production
      VERTICAL_TEXT_GENERATOR_URL: http://vertical-text-generator:8000
    command: ['node', 'scripts/worker.js']
    restart: unless-stopped
    depends_on:
      - vertical-text-generator
    healthcheck:
      test: ['CMD', 'node', '-e', 'process.exit(0)']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  vertical-text-generator:
    build:
      context: ./vertical_text_generator
    ports:
      - '8000:8000'
    environment:
      PORT: 8000
      PYTHONPATH: /app
      PRELOAD_FONTS: 1
      FONT_MEMORY_RESERVE_MB: 128
      PAGE_POOL_SIZE: 8
      PRECREATE_PAGES: 1
      WARMUP_RENDER_ON_STARTUP: 1
      WEB_CONCURRENCY: 4
      GUNICORN_TIMEOUT: 180
      GUNICORN_GRACEFUL_TIMEOUT: 30
      GUNICORN_KEEPALIVE: 5
      GUNICORN_MAX_REQUESTS: 0
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  database:
    driver: local
  storage:
    driver: local
  local_storage:
    driver: local
  logs:
    driver: local

networks:
  default:
    driver: bridge
