services:
  web:
    user: "1000:1000"  # 環境変数に依存せず直接指定
    build:
      context: .
      target: production
    ports:
      - '3000:3000'
    volumes:
      - ./:/app # ソースコードのみマウント
      # Mount source code but keep the container-built node_modules by
      # mapping the named volume `node_modules` into the container path.
      - node_modules:/app/node_modules
      # Persist Next.js cache between restarts to avoid full recompiles on the
      # first request after container restart.
      - next_cache:/app/.next
    env_file:
      - .env
    environment:
      NODE_ENV: production
      VERTICAL_TEXT_GENERATOR_URL: http://vertical-text-generator:8000
    # Ensure node_modules volume is seeded from image-installed modules
    command: ['/usr/local/bin/ensure-node-modules.sh', 'npm', 'run', 'start']
    depends_on:
      - vertical-text-generator

  vertical-text-generator:
    build:
      context: ./vertical_text_generator
    ports:
      - '8000:8000'
    volumes:
      - ./vertical_text_generator:/app
    environment:
      PORT: 8000
      PYTHONPATH: /app
      PRELOAD_FONTS: 1
      FONT_MEMORY_RESERVE_MB: 128
      PAGE_POOL_SIZE: 8
      PRECREATE_PAGES: 1
      WARMUP_RENDER_ON_STARTUP: 1
      WEB_CONCURRENCY: 4
      GUNICORN_TIMEOUT: 180
      GUNICORN_GRACEFUL_TIMEOUT: 30
      GUNICORN_KEEPALIVE: 5
      GUNICORN_MAX_REQUESTS: 0

volumes:
  node_modules:
  next_cache:
  database:
