import next from 'eslint-config-next'

export default [
  {
    ignores: [
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.spec.ts',
      '**/*.spec.tsx',
      '**/__tests__/**/*',
      'vitest.setup.ts',
      'vitest.config.ts',
      'workers/**/*',
      'tmp_test/**/*',
      '.next/**/*',
      'node_modules',
      'out',
      'dist',
      'build',
      '.open-next',
      '.opennext-cache',
      '.next/cache',
      '.next/server',
      '.next/static',
      '.next/trace',
      'logs',
      '*.log',
      '.env*',
      '.DS_Store',
      'Thumbs.db',
      '.vscode',
      '.idea',
      '.wrangler',
      '.miniflare',
      '*.db',
      '*.sqlite',
      '*.sqlite3',
      'coverage',
      '.nyc_output',
      '*.tsbuildinfo',
      '.mastra',
      // Generated by `wrangler types` (contains bare `Function` types etc.)
      'cloudflare-env.d.ts',
    ],
  },
  ...next,
  {
    files: ['**/*.{js,jsx,ts,tsx,mts}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@/utils/api-error-response',
              message:
                "Deprecated: Use createErrorResponse and ApiError from '@/utils/api-error' instead.",
            },
            {
              name: 'src/utils/api-error-response',
              message:
                "Deprecated: Use createErrorResponse and ApiError from '@/utils/api-error' instead.",
            },
            {
              name: './src/utils/api-error-response',
              message:
                "Deprecated: Use createErrorResponse and ApiError from '@/utils/api-error' instead.",
            },
            {
              name: 'src\\utils\\api-error-response',
              message:
                "Deprecated: Use createErrorResponse and ApiError from '@/utils/api-error' instead.",
            },
          ],
        },
      ],
    },
  },
  // Disallow new HttpError usage in API routes (use ApiError hierarchy instead)
  {
    files: ['src/app/api/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          // API ルートでは旧来の HttpError の使用を禁止
          patterns: [
            {
              group: [
                '@/utils/http-errors',
                'src/utils/http-errors',
                './src/utils/http-errors',
                '**/utils/http-errors',
              ],
              message:
                'Use ApiError and createErrorResponse (src/utils/api-error) instead of HttpError in routes.',
            },
            // 将来的な混入防止: Cloudflare 依存の禁止（OpenNext 依存の除去方針）
            {
              group: ['@opennextjs/cloudflare', '@opennextjs/cloudflare/*'],
              message:
                'API ルートでは @opennextjs/cloudflare の import を禁止します。環境は Effect の Layer や標準の環境変数経由で注入してください。',
            },
            // API ルートでの '@/db' 直接参照を禁止（型 import は許可）
            {
              group: ['@/db', 'src/db', '@/db/index'],
              message:
                "API ルートでの直接DB参照は禁止です。'@/services/database' のファクトリを経由してください。型のみの import は 'import type' を使用してください。",
            },
          ],
          // 明示的なパス指定でも禁止
          paths: [
            {
              name: '@opennextjs/cloudflare',
              message:
                'API ルートでは @opennextjs/cloudflare の import を禁止します。環境は Effect の Layer や標準の環境変数経由で注入してください。',
            },
            {
              name: '@/db',
              message:
                "API ルートでの直接DB参照は禁止です。'@/services/database' のファクトリを経由してください。型のみの import は 'import type' を使用してください。",
            },
          ],
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: "NewExpression[callee.name='HttpError']",
          message:
            'Do not instantiate HttpError in routes. Throw ApiError or a subclass (e.g., ValidationError, NotFoundError).',
        },
        {
          selector: "InstanceofExpression[right.name='HttpError']",
          message:
            'Do not type-check against HttpError in routes. Use ApiError (or rely on createErrorResponse).',
        },
        {
          selector: "ClassDeclaration[superClass.name='HttpError']",
          message:
            'Do not declare HttpError subclasses in routes. Define domain-specific ApiError subclasses in shared utils if needed.',
        },
      ],
    },
  },
  // Disallow HttpError usage project-wide (except compatibility layer)
  // and forbid direct '@/db' imports outside tests (use services/database factory instead).
  {
    files: ['**/*.{ts,tsx,js,jsx}'],
    excludedFiles: [
      'src/utils/api-error.ts',
      'src/utils/http-errors.ts',
      '**/*.test.*',
      '**/*.spec.*',
      '**/__tests__/**',
      // Databaseブートストラップは例外（ファクトリ初期化のために '@/db' を呼ぶ）
      'src/services/database/index.ts',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          allowTypeImports: true,
          paths: [
            {
              name: '@/utils/http-errors',
              message: 'HttpError is deprecated. Use ApiError hierarchy instead.',
            },
            {
              name: 'src/utils/http-errors',
              message: 'HttpError is deprecated. Use ApiError hierarchy instead.',
            },
            {
              name: '@/db',
              message:
                "アプリ層での直接DB参照は禁止です。'@/services/database' のファクトリを経由してください。型のみの import は 'import type' を使用してください。",
            },
            {
              name: 'src/db',
              message:
                "アプリ層での直接DB参照は禁止です。'@/services/database' のファクトリを経由してください。型のみの import は 'import type' を使用してください。",
            },
          ],
          patterns: [
            {
              group: ['**/db/index', './src/db', '@/db', '@/db/*'],
              message:
                "アプリ層での直接DB参照は禁止です。'@/services/database' のファクトリを経由してください。型のみの import は 'import type' を使用してください。",
            },
          ],
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: "NewExpression[callee.name='HttpError']",
          message: 'HttpError is deprecated. Use ApiError hierarchy instead.',
        },
      ],
    },
  },
  {
    files: [
      '**/*.test.ts',
      '**/*.spec.ts',
      '**/*.test.tsx',
      '**/*.spec.tsx',
      '**/__tests__/**/*.ts',
      '**/__tests__/**/*.tsx',
    ],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
    },
  },
]
