import next from 'eslint-config-next'

export default [
  {
    ignores: [
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.spec.ts',
      '**/*.spec.tsx',
      '**/__tests__/**/*',
      'vitest.config.ts',
      'workers/**/*',
      'tmp_test/**/*',
      '.next/**/*',
      'node_modules',
      'out',
      'dist',
      'build',
      '.open-next',
      '.opennext-cache',
      '.next/cache',
      '.next/server',
      '.next/static',
      '.next/trace',
      'logs',
      '*.log',
      '.env*',
      '.DS_Store',
      'Thumbs.db',
      '.vscode',
      '.idea',
      '.wrangler',
      '.miniflare',
      '*.db',
      '*.sqlite',
      '*.sqlite3',
      'coverage',
      '.nyc_output',
      '*.tsbuildinfo',
      '.mastra',
    ],
  },
  ...next,
]
