main = ".open-next/worker.js"
name = "novel2manga-mastra"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# 環境変数の設定（開発時はローカルの.envから読み込み）
# 本番環境ではCloudflareダッシュボードで設定
# [vars]
# OPENAI_API_KEY = "your-api-key"

# AI bindingの設定（必要に応じて）
# [ai]
# binding = "AI"

# KV namespaceの設定（キャッシュ用）
[[kv_namespaces]]
binding = "CACHE"
id = "45024d55bd654f8fad87d854c4171868"
preview_id = "5d1480c30cd04fdc95ed18d741c9531b"

[[kv_namespaces]]
binding = "NEXT_INC_CACHE_KV"
id = "OPENNEXT_INCREMENTAL_CACHE_KV_NAMESPACE_ID"
preview_id = "OPENNEXT_INCREMENTAL_CACHE_KV_PREVIEW_ID"

# D1データベースの設定（必要に応じて）
[[d1_databases]]
binding = "DB"
database_name = "novel2manga"
database_id = "f920ec55-c48d-4f3a-85e3-c1a8032962a7"

[[d1_databases]]
binding = "NEXT_TAG_CACHE_D1"
database_name = "opennext-tag-cache"
database_id = "OPENNEXT_TAG_CACHE_D1_DATABASE_ID"

# R2バケットの設定
[[r2_buckets]]
binding = "NOVEL_STORAGE"
bucket_name = "novel-storage"

[[r2_buckets]]
binding = "CHUNKS_STORAGE"
bucket_name = "chunks-storage"

[[r2_buckets]]
binding = "ANALYSIS_STORAGE"
bucket_name = "analysis-storage"

[[r2_buckets]]
binding = "LAYOUTS_STORAGE"
bucket_name = "layouts-storage"

[[r2_buckets]]
binding = "RENDERS_STORAGE"
bucket_name = "renders-storage"

[[r2_buckets]]
binding = "OUTPUTS_STORAGE"
bucket_name = "outputs-storage"

# D1データベースの設定（開発環境ではローカルSQLiteを使用）

# Cloudflare Queue設定
[[queues.producers]]
binding = "JOBS_QUEUE"
queue = "novel2manga-jobs"

[[queues.consumers]]
queue = "novel2manga-jobs"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 3