name = "novel2manga-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "novel2manga"
database_id = "f920ec55-c48d-4f3a-85e3-c1a8032962a7"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "novel2manga-storage"

[vars]
ENVIRONMENT = "development"