name: CI Basic

on:
  push:
    branches: [main, feat/**]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (clean)
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --no-audit --no-fund

      - name: Type Check
        run: npm run typecheck

      - name: Lint & Format Check
        run: npm run check:ci

      - name: Unit Tests
        run: npm run test:unit -- --run --reporter=verbose

      - name: Summary
        if: always()
        run: |
          echo 'Typecheck / Lint / Unit tests finished.'
