name: Manual Placeholder

# 手動実行専用のプレースホルダ。自動トリガーを増やす前の安全策として残している。
# 必要になったらこのファイルを削除してもよい。
on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "CI temporarily minimized. Add workflows as needed."
