name: PR Checklist Guard

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR checklist and required links
        uses: actions/github-script@v7
        with:
          script: |
            // PR checklist validation disabled - always pass
            core.info('PR checklist validation skipped (disabled).');
